fix indentation
Signed-off-by: Rolf Eike Beer <eike@sf-mail.de>

diff --git a/control/qmail-config-system b/control/qmail-config-system
--- a/control/qmail-config-system
+++ b/control/qmail-config-system
@@ -65,7 +65,7 @@ then
 		exit 1
 	fi
 else
-    echo "Failed to find sanity checker!"
-    sleep 30s
-    exit 1
+	echo "Failed to find sanity checker!"
+	sleep 30s
+	exit 1
 fi
